### ISSUE TITLE
Example from README fails in 'plot_frames_in'

### ISSUE THREAD

**Issue by comkieffer** [rock-learning/pytransform3d#58]
When running the example included in the README, the following error occurs. This was tested in a new virtualenv with the following versions of dependencies:

``` 
beautifulsoup4==4.9.1
cycler==0.10.0
kiwisolver==1.2.0
lxml==4.5.2
matplotlib==3.3.0
numpy==1.19.0
pillow==7.2.0
pydot==1.4.1
pyparsing==2.4.7
python-dateutil==2.8.1
pytransform3d==1.2
scipy==1.5.1
six==1.15.0
soupsieve==1.9.6
trimesh==3.7.10
```

The traceback is: 
```
Traceback (most recent call last):
  File "transformations-test.py", line 24, in <module>
    ax = tm.plot_frames_in("robot", s=0.1)
  File "/home/tch/.cache/pypoetry/virtualenvs/pytransform-test-epSAifj1-py3.6/lib/python3.6/site-packages/pytransform3d/transform_manager.py", line 210, in plot_frames_in
    strict_check=self.strict_check, **kwargs)
  File "/home/tch/.cache/pypoetry/virtualenvs/pytransform-test-epSAifj1-py3.6/lib/python3.6/site-packages/pytransform3d/transformations.py", line 413, in plot_transform
    frame = Frame(A2B, name, s, **kwargs)
  File "/home/tch/.cache/pypoetry/virtualenvs/pytransform-test-epSAifj1-py3.6/lib/python3.6/site-packages/pytransform3d/plot_utils.py", line 48, in __init__
    self.set_data(A2B, label)
  File "/home/tch/.cache/pypoetry/virtualenvs/pytransform-test-epSAifj1-py3.6/lib/python3.6/site-packages/pytransform3d/plot_utils.py", line 67, in set_data
    b.set_3d_properties([p[2], p[2] + self.s * R[2, d]])
  File "/home/tch/.cache/pypoetry/virtualenvs/pytransform-test-epSAifj1-py3.6/lib/python3.6/site-packages/mpl_toolkits/mplot3d/art3d.py", line 143, in set_3d_properties
    zs = np.broadcast_to(zs, xs.shape)
AttributeError: 'list' object has no attribute 'shape'
```

**Comment by AlexanderFabisch** [comment]
Hi, thanks for reporting. The example works on my machine so it should be related to the specific versions that you use. I will have a look.

**Comment by AlexanderFabisch** [comment]
Please check the current master. This should fix the issue.

**Comment by comkieffer** [comment]
Works on my end. Thanks for the insanely fast turn around.

**Comment by wagenaartje** [comment]
I'm still experiencing this exact error. Any quick fixes?

**Comment by comkieffer** [comment]
I'm not sure if this fix has been pushed to pip. Cloning the repo from github directly should solve your issue.

**Comment by wagenaartje** [comment]
Ah yes you're right, thanks!

**Comment by AlexanderFabisch** [comment]
No, there is not a new version on PyPI yet. You can use pip to install from git directly:

```
pip install git+git://github.com/rock-learning/pytransform3d.git
```

**Comment by AlexanderFabisch** [comment]
...but that reminds me that I should probably make a minor version increment on PyPI.

**Comment by AlexanderFabisch** [comment]
> ...but that reminds me that I should probably make a minor version increment on PyPI.

Version 1.2.1 is available now.
